//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JM.QingQi
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int logo = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060005
			public const int buttonDeviceInfo = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int buttonSelectedTypes = 2131099652;
			
			// aapt resource value: 0x7f060003
			public const int deviceInfoListView = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int itemList = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int scrollView01 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int tableLayout = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int tableLayout1 = 2131099654;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DataStream = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DataStreamSelected = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int DeviceInfo = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int TroubleCode = 2130903044;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040009
			public const int ActiveTest = 2130968585;
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int Clear = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int ClearTroubleCode = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int DeviceID = 2130968581;
			
			// aapt resource value: 0x7f040002
			public const int DeviceInfo = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Model = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int Read = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int ReadLiveData = 2130968584;
			
			// aapt resource value: 0x7f040006
			public const int ReadTroubleCode = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int SelectedTypes = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int Version = 2130968580;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050001
			public const int Theme_Default = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Theme_Splash = 2131034112;
			
			private Style()
			{
			}
		}
	}
}
